server {
    listen 9528;
    server_name _;

    location = / {
        return 302 /flow/;
    }

    location = /flow {
        return 301 /flow/;
    }

    location = /flow/index.html {
        alias /home/rsh-flow-components/dist/index.html;
    }

    location /flow/ {
        alias /home/rsh-flow-components/dist/;
        index index.html;
        try_files $uri $uri/ /flow/index.html;
    }
}
