const formMainConfig = [
  [
    {
      type:'label',
      title:'项目名称',
      span:5,
    },
    {
      type:'input',
      prop:'projectName',
      placeholder:'请输入项目名称',
      span:19,
      value:'',
      maxlength:200,
      rules:[
        { required: true, message: '项目名称不能为空'},
      ]
    }
  ],
  [
    {
      type:'label',
      title:'招标采购项目概况',
      span:5,
    },
    {
      type:'textarea',
      prop:'projectOverview',
      placeholder:'',
      maxlength:1000,
      span:19,
      value:''
    }
  ],
  [
    {
      type:'label',
      title:'招标/采购人单位名称',
      span:5,
    },
    {
      type:'select',
      options:[],
      prop:'procureCompanyId',
      span:19,
      value:''
    }
  ],
  [
    {
      type:'label',
      title:'是否委托招标',
      span:5,
    },
    {
      type:'select',
      options:[
        {label:'是',value:'1'},
        {label:'否',value:'0'},
      ],
      prop:'entrust',
      span:7,
      value:'0',
      changeEvent:()=>{}
    },
    {
      type:'label',
      title:'委托招标采购代理机构单位名称',
      span:5,
    },
    {
      type:'select',
      options:[],
      // allowCreate:true,
      filterable:true,
      prop:'entrustCompanyId',
      span:7,
      value:'',
      disabled:true
    },
  ],
]

const formContentConfig = [
  [
      {
        type:'label',
        title:'标段划分',
        span:5,
      },
      {
        type:'textarea',
        prop:'sectionDivide',
        span:19,
        value:'',
        maxlength:1000,
      }
    ],
    [
      {
        type:'label',
        title:'标段编号',
        span:5,
      },
      {
        type:'input',
        prop:'sectionCode',
        span:7,
        value:'',
        maxlength:200,
        borderRight:'',
      },
      {
        type:'label',
        title:'标段范围',
        span:5,
      },
      {
        type:'textarea',
        prop:'sectionRange',
        span:7,
        value:'',
        maxlength:1000,
      }
    ],
    [
      {
        type:'label',
        title:'合同发包模式',
        span:5,
      },
      {
        type:'select',
        options:[
          {label:'单价合同',value:'unitPrice'},
          {label:'总价合同',value:'totalPrice'},
          {label:'费率合同',value:'rate'},
          {label:'成本加酬金',value:'costCompensation'},
        ],
        prop:'contractMode',
        span:12,
        value:''
      }
    ],
    [
      {
        type:'label',
        title:'合同付款节点',
        span:5,
      },
      {
        type:'input',
        placeholder:'例如：首付30%...',
        prop:'paymentNode',
        span:19,
        value:'',
        maxlength:200,
      }
    ],
    [
      {
        type:'label',
        title:'招标采购形式',
        span:5,
      },
      {
        type:'select',
        options:[
          {label:'公开招标',value:'open'},
          {label:'邀请招标',value:'invitation'},
          {label:'询比采购',value:'inquiry'},
          {label:'竞争性谈判采购',value:'negotiations'},
          {label:'竞争性磋商采购',value:'consult'},
          {label:'框架协议采购',value:'framework'},
          {label:'单一来源采购',value:'singleSource'},
        ],
        prop:'procureWay',
        span:12,
        value:''
      }
    ],
    [
      {
        type:'label',
        title:'评审办法',
        span:5,
      },
      {
        type:'input',
        prop:'reviewWay',
        span:19,
        value:'',
        maxlength:1000,
      }
    ],
    [
      {
        type:'label',
        title:'评审专家组织',
        span:5,
      },
      {
        type:'input',
        prop:'expertOrganization',
        span:19,
        value:'',
        maxlength:1000,
      }
    ],
    [
      {
        type:'label',
        title:'预计挂网时间',
        span:5,
      },
      {
        type:'date',
        dateType:'datetime',
        prop:'sellDate',
        span:7,
        value:''
      },
      {
        type:'label',
        title:'预计开标时间',
        span:5,
      },
      {
        type:'date',
        dateType:'datetime',
        prop:'bidOpeningDate',
        span:7,
        value:'',
        pickerOptions:""
      }
    ]
  ]
export {formMainConfig,formContentConfig}
