CREATE TABLE test_form_runtime_sync_jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  status VARCHAR(16) NOT NULL,
  stage VARCHAR(24) NOT NULL,
  active_guard TINYINT UNSIGNED NULL,
  source_repository VARCHAR(128) NOT NULL,
  source_branch VARCHAR(128) NOT NULL,
  source_head CHAR(40) NOT NULL,
  source_dirty TINYINT(1) NOT NULL,
  source_changed_files JSON NOT NULL,
  source_inspected_at DATETIME(3) NOT NULL,
  candidate_version VARCHAR(128) NULL,
  previous_version VARCHAR(128) NULL,
  failure_reason VARCHAR(1000) NULL,
  recovery_status VARCHAR(24) NOT NULL DEFAULT 'NOT_REQUIRED',
  recovery_message VARCHAR(1000) NULL,
  lease_owner VARCHAR(128) NULL,
  lease_expires_at DATETIME(3) NULL,
  fencing_token BIGINT UNSIGNED NOT NULL DEFAULT 0,
  attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL,
  started_at DATETIME(3) NULL,
  updated_at DATETIME(3) NOT NULL,
  completed_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_test_form_runtime_sync_active (active_guard),
  KEY idx_test_form_runtime_sync_status_lease (status, lease_expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
