CREATE TABLE test_path_preparation_jobs (
  id CHAR(36) NOT NULL,
  plan_id BIGINT UNSIGNED NOT NULL,
  create_key CHAR(36) NOT NULL,
  status VARCHAR(24) NOT NULL,
  total_count INT UNSIGNED NOT NULL,
  processed_count INT UNSIGNED NOT NULL DEFAULT 0,
  node_configured_count INT UNSIGNED NOT NULL DEFAULT 0,
  data_generated_count INT UNSIGNED NOT NULL DEFAULT 0,
  needs_attention_count INT UNSIGNED NOT NULL DEFAULT 0,
  failed_count INT UNSIGNED NOT NULL DEFAULT 0,
  preserved_manual_count INT UNSIGNED NOT NULL DEFAULT 0,
  failure_reason VARCHAR(500) NOT NULL DEFAULT '',
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  completed_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_test_path_preparation_create (create_key),
  KEY idx_test_path_preparation_plan_status_updated (plan_id, status, updated_at),
  CONSTRAINT fk_test_path_preparation_plan FOREIGN KEY (plan_id) REFERENCES test_plans (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
