CREATE TABLE IF NOT EXISTS test_template_rule_catalog (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  source_template_id VARCHAR(128) NOT NULL,
  flow_code VARCHAR(255) NOT NULL,
  flow_name VARCHAR(255) NOT NULL,
  template_type VARCHAR(255) NOT NULL,
  form_exist VARCHAR(64) NOT NULL,
  render_type VARCHAR(32) NOT NULL,
  source_account VARCHAR(255) NOT NULL,
  source_version VARCHAR(255) NOT NULL,
  source_fingerprint CHAR(64) NOT NULL,
  analyzer_version VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  rule_data JSON NOT NULL,
  coverage JSON NOT NULL,
  issues JSON NOT NULL,
  analyzed_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY uk_template_rule_catalog_source (source_template_id),
  KEY idx_template_rule_catalog_flow (flow_code),
  KEY idx_template_rule_catalog_render (render_type),
  KEY idx_template_rule_catalog_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS test_template_rule_analysis_jobs (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  mode VARCHAR(32) NOT NULL,
  account VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL,
  total_count INT NOT NULL DEFAULT 0,
  processed_count INT NOT NULL DEFAULT 0,
  completed_count INT NOT NULL DEFAULT 0,
  needs_attention_count INT NOT NULL DEFAULT 0,
  failed_count INT NOT NULL DEFAULT 0,
  message VARCHAR(500) NOT NULL DEFAULT '',
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  finished_at DATETIME(3) NULL,
  KEY idx_template_rule_jobs_account (account, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
