const formMainConfig = [
  [
    {
      type:'label',
      title:'合同名称',
      span:5,
    },
    {
      type:'select',
      prop:'contractNameId',
      span:19,
      options:[],
      value:'',
      changeEvent:()=>{},
      rules:[
        { required: true, message: '合同名称不能为空',trigger:'change'},
      ]
    }
  ],
  [
    {
      type:'label',
      title:'合同编号',
      span:5,
    },
    {
      type:'input',
      prop:'contractNumber',
      placeholder:'请输入合同编号',
      span:7,
      value:''
    },
    {
      type:'label',
      title:'合同类型',
      span:5,
    },
    {
      type:'select',
      options:[
        {value:'server',label:'服务类'},
        {value:'material',label:'材料类'},
        {value:'engineering',label:'工程类'},
        {value:'device',label:'设备类'}
      ],
      prop:'contractType',
      span:7,
      value:'server'
    },
  ],
  [
    {
      type:'label',
      title:'合同主体',
      span:5,
    },
    {
      span:19,
      children:[
        [
          {
            type:'label',
            title:'甲方',
            span:4,
          },
          {
            type:'select',
            options:[],
            prop:'firstPartyId',
            span:8,
            value:'',
            disabled:true
          },
          {
            type:'label',
            title:'法定代表人',
            span:4,
          },
          {
            type:'input',
            prop:'firstPartyCorporation',
            span:8,
            value:''
          },
        ],
        [
          {
            type:'label',
            title:'乙方',
            span:4,
          },
          {
            type:'select',
            prop:'secondPartyId',
            placeholder:'',
            span:8,
            value:'',
            options:[],
            rules:[
              { required: true, message: '乙方不能为空',trigger:'change'},
            ]
          },
          {
            type:'label',
            title:'法定代表人',
            span:4,
          },
          {
            type:'input',
            prop:'secondPartyCorporation',
            placeholder:'',
            span:8,
            value:''
          },
        ],
      ]
    }
  ],
  [
    {
      type:'label',
      title:'合同范围',
      span:5,
    },
    {
      type:'textarea',
      prop:'contractRange',
      span:19,
      maxlength:1000,
      value:''
    }
  ],
  [
    {
      type:'label',
      title:'支付方式',
      span:5,
    },
    {
      type:'textarea',
      prop:'payMethod',
      span:19,
      value:'',
      maxlength:1000,
      placeholder:'进度款支付描述'
    }
  ],
  [
    {
      type:'label',
      title:'结算办法',
      span:5,
    },
    {
      type:'textarea',
      prop:'settlementMethod',
      span:19,
      value:'',
      maxlength:1000,
      placeholder:'合同款计量方式'
    }
  ],
  [
    {
      type:'label',
      title:'收款账号',
      span:5,
    },
    {
      span:19,
      children:[
        [
          {
            type:'label',
            title:'收款账号',
            span:5,
          },
          {
            type:'input',
            prop:'paymentAccount',
            span:9,
            value:'',
            placeholder:''
          }
        ],
        [
          {
            type:'label',
            title:'开户行',
            span:5,
          },
          {
            type:'input',
            prop:'bank',
            span:9,
            value:'',
            placeholder:''
          }
        ],
        [
          {
            type:'label',
            title:'开户行行号',
            span:5,
          },
          {
            type:'input',
            prop:'lineNumber',
            span:9,
            value:'',
            placeholder:''
          }
        ],
      ]
    }
  ],
  [
    {
      type:'label',
      title:'合同谈判方式',
      span:5,
    },
    {
      type:'radio',
      prop:'contractTalk',
      options:[
        {label:'公开招标',value:'open'},
        {label:'邀请招标',value:'invitation'},
        {label:'询比采购',value:'inquiry'},
        {label:'竞争性谈判采购',value:'negotiations'},
        {label:'竞争性磋商采购',value:'consult'},
        {label:'框架协议采购',value:'framework'},
        {label:'单一来源采购',value:'singleSource'},
        // {label:'其他'},
      ],
      span:19,
      value:'',
    },
  ],
  [
    {
      type:'label',
      title:'合同金额',
      span:5,
    },
    {
      span:19,
      children:[
        [
          {
            type:'label',
            title:'小写',
            span:5,
          },
          {
            type:'inputNum',
            prop:'contractSum',
            span:9,
            value:'',
            placeholder:'',
            inputEvent:()=>{},
            rules:[
              { required: true, message: '合同金额不能为空'},
            ]
          },
          {
            type:'label',
            title:'大写',
            span:5,
          },
          {
            type:'input',
            prop:'contractSumUp',
            span:9,
            value:'',
            placeholder:'',
            disabled:true
          }
        ]
      ]
    }
  ],
  [
    {
      type:'label',
      title:'银行支付方式',
      span:5,
    },
    {
      type:'select',
      options:[
        {label:'现金',value:'cash'},
        {label:'支票',value:'cheque'},
        {label:'汇票',value:'draft'},
        {label:'电汇',value:'WireTransfer'},
        {label:'银行承兑',value:'bankHonour'},
        {label:'其他',value:'other'},
      ],
      prop:'bankPayMethod',
      span:7,
      value:''
    },
    {
      type:'label',
      title:'发票类型',
      span:5,
    },
    {
      type:'input',
      prop:'billType',
      span:7,
      value:'',
      placeholder:'',
    }
  ],
  [
    {
      type:'label',
      title:'合同起草人',
      span:5,
    },
    {
      type:'radio',
      options:[
        {label:'对方起草',value:'draft'},
        {label:'同经办人',value:'handledBy'},
      ],
      prop:'contractDrafter',
      span:7,
      value:'handledBy'
    },
    {
      type:'label',
      title:'经办人',
      span:5,
    },
    {
      type:'input',
      prop:'handledBy',
      span:7,
      value:'',
      placeholder:'',
    }
  ]
]
export default formMainConfig
