import type {
  PlanRow,
} from './types.ts'

export const mockPlans: PlanRow[] = [
  {
    id: 'plan-001',
    name: '采购申请主流程回归',
    flowName: '采购申请审批',
    accountName: '张敏（zhangmin）',
    pathCount: 0,
    runMode: 'serial',
    scheduledAt: null,
    status: 'not_started',
    lastRunResult: '尚未运行',
  },
  {
    id: 'plan-002',
    name: '合同用印条件分支检查',
    flowName: '合同用印审批',
    accountName: '李伟（liwei）',
    pathCount: 3,
    runMode: 'parallel',
    scheduledAt: '2026-07-28 09:30',
    status: 'not_started',
    lastRunResult: '尚未运行',
  },
  {
    id: 'plan-003',
    name: '费用报销日常巡检',
    flowName: '费用报销审批',
    accountName: '测试专员（tester01）',
    pathCount: 4,
    runMode: 'serial',
    scheduledAt: null,
    status: 'running',
    lastRunResult: '2 / 4 路径已完成',
  },
  {
    id: 'plan-004',
    name: '项目立项完整路径验证',
    flowName: '项目立项审批',
    accountName: '李伟（liwei）',
    pathCount: 5,
    runMode: 'parallel',
    scheduledAt: '2026-07-26 18:00',
    status: 'completed',
    lastRunResult: '成功 5，失败 0',
  },
]
